### ISSUE TITLE
errRequestOutdatedClientVersion

### ISSUE THREAD

**Issue by Stevio2000** [Zweer/BigBangEmpireBot#2]
Hello,

I get an error when executing the script:

```
15:18:08 - init started
15:18:10 - initFriendBar started
15:18:10 - initGame started
Error: errRequestOutdatedClientVersion @ initGame {"locale":"en_US","swf_ui_hash":"db8ae3f4229f9dc513bf86090382d8fc","swf_character_hash":"c78c7f823150f019e7fd3515cb78d25a","swf_main_hash":"8af82af56d992b48680d0f5aa0883b2a","no_text":true,"user_id":0,"rct":1,"action":"initGame","client_version":"flash_42","user_session_id":0,"auth":"8aca871eea2595a0d06c1026bf3c9d50"}
    at request.post.then (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\app\lib\bbe.js:179:17)
    at tryCatcher (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Steve\Desktop\BBE\BigBangEmpireBot-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by demis666** [comment]
hi i also get JScript error. Is this still working?

**Comment by Zweer** [comment]
Nope, the official client has a newer version and, sorry, I've no time to fix it... probably it only requires a bump in the client version...
